# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Singlekorn GitHub Pages
email: chris.einkorn@singlekorn.com
description: >- # this means to ignore newlines until "baseurl:"
  Test bed for Jekyll and GitHub actions for static content
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://singlekorn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: singlekorn
github_username:  singlekorn

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# just-the-docs theme configuration
logo: "/assets/oct.png"
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 3
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "Singlekorn Resume":
    - "//resume.singlekorn.com"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-Y76N7ES72M
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
